# Generated by Django 5.0.7 on 2024-09-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noc',
            name='no_of_travelers',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='noc',
            name='passport_copy',
            field=models.FileField(default='default/path/to/file.jpg', upload_to='passport_copies/'),
        ),
    ]
