# Generated by Django 5.0.7 on 2024-10-05 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_alter_noc_no_of_travelers_alter_noc_passport_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushernotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pusher_notifications', to='profileapp.employees'),
        ),
    ]
