# Generated by Django 5.0.7 on 2024-09-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rrfemployee',
            name='HODID',
            field=models.CharField(max_length=8),
        ),
    ]
