# Generated by Django 5.0.7 on 2024-09-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_alter_rrfemployee_hodid'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOCCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('concern', models.CharField(max_length=500)),
                ('embassy', models.CharField(max_length=500)),
                ('office_address', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='noc',
            name='to_desg',
        ),
        migrations.RemoveField(
            model_name='noc',
            name='to_ofc',
        ),
    ]
