# Generated by Django 5.0.7 on 2024-09-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_noccountry_remove_noc_to_desg_remove_noc_to_ofc'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='BU_HeadID',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='Gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='HODID',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='Joining_Date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='UnitID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
