# Generated by Django 5.0.7 on 2024-09-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_employees_bu_headid_employees_gender_employees_hodid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa', models.CharField(max_length=200)),
                ('ref_code', models.CharField(max_length=8)),
                ('subject', models.TextField()),
                ('cost_provider', models.CharField(max_length=200)),
                ('intention', models.CharField(max_length=200)),
            ],
        ),
    ]
