# Generated by Django 5.0.7 on 2024-08-28 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0019_alter_expense_utility'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.CharField(max_length=20, unique=True)),
                ('applicant_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('travel_date_from', models.DateField()),
                ('travel_date_to', models.DateField()),
                ('type', models.CharField(choices=[('NOC', 'NOC'), ('Immigration', 'Immigration')], max_length=20)),
                ('type_noc', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_name', models.CharField(max_length=100)),
                ('passport_no', models.CharField(max_length=50)),
                ('passport_copy', models.FileField(blank=True, null=True, upload_to='passport_copies/')),
                ('invitation_letter', models.FileField(blank=True, null=True, upload_to='invitation_letters/')),
                ('country_visit', models.CharField(max_length=100)),
                ('no_of_travelers', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalTraveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_with_traveler', models.CharField(max_length=100)),
                ('additional_passport_name', models.CharField(max_length=100)),
                ('additional_passport_no', models.CharField(max_length=50)),
                ('additional_passport_copy', models.FileField(blank=True, null=True, upload_to='additional_passport_copies/')),
                ('travel_recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_travelers', to='profileapp.noc')),
            ],
        ),
    ]
