# Generated by Django 5.0.7 on 2024-08-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0019_alter_expense_utility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Unit', models.CharField(blank=True, max_length=100, null=True)),
                ('Department', models.CharField(blank=True, max_length=50, null=True)),
                ('Grade', models.CharField(blank=True, max_length=50, null=True)),
                ('Designation', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('ContactNo', models.CharField(blank=True, max_length=15, null=True)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Head_of_Dept', models.CharField(blank=True, max_length=100, null=True)),
                ('BU_Head', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='ExecutiveDirectors',
            fields=[
                ('EDID', models.IntegerField(primary_key=True, serialize=False)),
                ('EDDesg', models.CharField(blank=True, max_length=100, null=True)),
                ('EDEmail', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Executive Director',
                'verbose_name_plural': 'Executive Directors',
                'db_table': 'Executive_Directors',
            },
        ),
        migrations.CreateModel(
            name='RRFEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HODID', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Designation', models.CharField(blank=True, max_length=100, null=True)),
                ('Unit', models.CharField(blank=True, max_length=100, null=True)),
                ('Department', models.CharField(blank=True, max_length=50, null=True)),
                ('BU_Head', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'RRF Employee',
                'verbose_name_plural': 'RRF Employees',
                'db_table': 'RRFEmployee',
            },
        ),
    ]
