# Generated by Django 5.0.7 on 2024-08-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0020_employee_executivedirectors_rrfemployee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='ExecutiveDirectors',
        ),
        migrations.DeleteModel(
            name='RRFEmployee',
        ),
    ]
