# Generated by Django 5.0.7 on 2024-08-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0020_noc_additionaltraveler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noc',
            name='applicant_id',
            field=models.CharField(max_length=20),
        ),
    ]
