# Generated by Django 5.0.7 on 2024-08-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0021_alter_noc_applicant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='noc',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
