# Generated by Django 5.0.7 on 2024-09-01 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0021_delete_employee_delete_executivedirectors_and_more'),
        ('profileapp', '0022_noc_approved'),
    ]

    operations = [
    ]
