# Generated by Django 5.0.7 on 2024-09-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0023_merge_20240901_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='noc',
            name='grade',
            field=models.CharField(default='D-3', max_length=100),
        ),
    ]
