# Generated by Django 5.0.7 on 2024-09-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0025_pushernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='noc',
            name='to_desg',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='noc',
            name='to_ofc',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
